### ISSUE TITLE
Disabling Float128 does not work

### ISSUE THREAD

**Issue by kursatyurt** [boostorg/math#1206]
In the develop branch disabling float128 flag does not work.

In my cmake file, I added flag

```cmake 
add_definitions(-DBOOST_MATH_DISABLE_FLOAT128)
```

I can compile on 1.86 without any problem; however, it does not compile when I switch to the development branch

```
third_party/boost_math/include/boost/math/tools/big_constant.hpp(52): error: "T (boost::math::tools::largest_float, const char *, const std::true_type &, const std::false_type &)" contains a 128-bit floating-point, which is not supported in device code
```
The latest commit I can compile is `07d97df50` if I traced it correctly.
