### ISSUE TITLE
Compilation errors on MSVC 14.0

### ISSUE THREAD

**Issue by Lastique** [boostorg/math#1275]
Recently, Boost.Math was modified in a way that fails to compile with MSVC 14.0. This affects downstream libraries, specifically Boost.Parameter tests (which depend on Boost.Graph, which depends on Boost.Math):

https://ci.appveyor.com/project/Lastique/parameter/builds/52243732/job/r4qrqpaklphyncrb?fullLog=true#L845

I know the warning says MSVC 14.0 is no longer supported, but I think the `Jamfile` in Boost.Math should list the requirements that exclude the build on this compiler, which it currently doesn't. At least, `cxx14_constexpr` is missing (if the warning is to be believed), and some other requirement (currently non-existing in Boost.Config) that checks the presence of `*_t` and `*_v` versions of type traits in `<type_traits>`.
